on: # Workflow to publish site by building project and deploying to GitHub Pages
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches: main

permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued
  cancel-in-progress: false # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: kotlinc *.kt -d .jar -jdk-home $JAVA_HOME_21_X64 && kotlin -classpath .jar MainKt > _site/index.html
      - uses: actions/upload-pages-artifact@main
      - uses: actions/deploy-pages@main
